version: "3"
# print 'task generate' in command line to generate .pb files
tasks:
  generate:
    aliases:
      - gen
    cmds:
      - protoc -I ../protos ../protos/auth/auth.proto --go_out ./gen/go --go_opt paths=source_relative --go-grpc_out ./gen/go --go-grpc_opt paths=source_relative